name: Create Release

on:
  workflow_dispatch:

permissions:
  contents: write  # Allows creating releases and uploading assets

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        project: 
          - name: cj2glb
            path: tools/cj2glb/cj2glb.csproj
        include:
          - os: ubuntu-latest
            rid: linux-x64
          - os: windows-latest
            rid: win-x64
          - os: macos-latest
            rid: osx-x64
    outputs:
      FullSemVer: ${{ steps.gitversion.outputs.FullSemVer }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Install GitVersion
      run: dotnet tool install --global GitVersion.Tool

    - name: Determine version
      id: gitversion
      run: echo "::set-output name=FullSemVer::$(dotnet-gitversion /output json /showvariable FullSemVer)"

    - name: Build ${{ matrix.project.name }}
      run: dotnet publish ./${{ matrix.project.path }} -c Release --self-contained -p:PublishAot=false -r ${{ matrix.rid }} -p:Version=${{ steps.gitversion.outputs.FullSemVer }} -o ./publish/${{ matrix.project.name }}

    - name: Zip ${{ matrix.project.name }} Artifact
      if: runner.os != 'Windows'
      run: |
        cd ./publish/${{ matrix.project.name }}
        zip -r ${{ matrix.project.name }}-${{ matrix.rid }}.zip ${{ matrix.project.name }}
    
    - name: Zip ${{ matrix.project.name }} Artifact
      if: runner.os == 'Windows'
      run: |
        cd ./publish/${{ matrix.project.name }}
        powershell Compress-Archive -Path ${{ matrix.project.name }}.exe -DestinationPath ${{ matrix.project.name }}-${{ matrix.rid }}.zip

    - name: Upload ${{ matrix.project.name }} Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.project.name }}-${{ matrix.rid }}
        path: ./publish/${{ matrix.project.name }}/${{ matrix.project.name }}-${{ matrix.rid }}.zip

  create_release:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ needs.build.outputs.FullSemVer }}
        release_name: Release ${{ needs.build.outputs.FullSemVer }}
        draft: false
        prerelease: true

  publish_assets:
    runs-on: ubuntu-latest
    needs: create_release
    strategy:
      matrix:
        rid: [linux-x64, win-x64, osx-x64]
        project: 
          - name: cj2glb
    steps:
    - name: Download ${{ matrix.project.name }} Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.project.name }}-${{ matrix.rid }}
        path: ./publish/${{ matrix.project.name }}

    - name: Upload ${{ matrix.project.name }} Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./publish/${{ matrix.project.name }}/${{ matrix.project.name }}-${{ matrix.rid }}.zip
        asset_name: ${{ matrix.project.name }}-${{ matrix.rid }}.zip
        asset_content_type: application/zip